export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const SEND_REGISTER_SUCCESS = 'SEND_REGISTER_SUCCESS';
export const SEND_REGISTER_FAIL = 'SEND_REGISTER_FAIL';

export const SEND_REFILL_SUCCESS = 'SEND_REFILL_SUCCESS';
export const SEND_REFILL_FAIL = 'SEND_REFILL_FAIL';
export const SEND_REFILL_START = 'SEND_REFILL_START';

export const SEND_INIT = 'SEND_INIT';
export const FETCH_REFILLS_SUCCESS = 'FETCH_REFILLS_SUCCESS';
export const FETCH_REFILLS_FAIL = 'FETCH_REFILLS_FAIL';
export const FETCH_REFILLS_START = 'FETCH_REFILLS_START';